### ISSUE TITLE
Stereoscopic Raymarching for VR?

### ISSUE THREAD

**Issue by acylum** [nicoptere/raymarching-for-THREE#2]
First,  
Your blog and this project are fantastic!   I was really amazed with Shadertoy, but I had no idea about what was going on with Ray marching - that is until I stumbled upon your blog and repo - great job!

So, now I am wondering about how to modify the shaders to produce a stereoscopic version that could be used for mobile VR? - like in google cardboard.

I've been looking at Mozilla's A-frame (it's webVR using Three.js)  and I'd like to try to create stereoscopic  Ray Marching shaders that could be used with an a-frame scene.

**Comment by dmarcos** [comment]
Hi, this is Diego from the aframe team. We would love to integrate raymarching examples. Let me know how I can help

**Comment by acylum** [comment]
Hi Diego - fantastic that you are from the aframe team!  I'm hoping that it would be possible to get ray marching frag shaders like this running in webvr!   https://www.shadertoy.com/view/XtS3DD

**Comment by omgitsraven** [comment]
Hey there -- I've just put together a component that should help you get started with that! https://github.com/omgitsraven/aframe-raytrace-component

**Comment by nicoptere** [comment]
ok I officially suck at maintaining repos, just seeing this now, 3 years later ....
glad @omgitsraven found a solution, it looks really nice :)
also, I don't think it's the best way to go: ray marching is computationally prohibitive and needs to be rendered twice which is a big nono for mobile devices.

**Comment by omgitsraven** [comment]
I think it's OK for some WebVR to be desktop-only, heh ;)

Also, the advantage of my component is, it doesn't have to render the entire screen—it's for placing individual raytraced objects into a scene that's otherwise polygonal. If you control how close the user is allowed to get to the object (which I admit is easier said than done in VR...) then you can limit how many pixels are actually spent raytracing, vs cheaply rasterizing polys for most of the scenery in the periphery.

Besides, even when doing the full scene raytraced, there's some neat effects you can make with very simple calculations... your average shadertoy demo will definitely be much too heavy, but I've seen some very cool ones that look nothing like you could do with polys, while also being very light on calculations! I say better to give people the chance to experiment, even if only some of the results will actually be VR-suitable, heh :)

**Comment by nicoptere** [comment]
agreed :)
I was referring to the demo posted above which seems too expensive "as is".
there's always room for fine-tuning/tricks/optimization but in most cases, you won't get away with a copy / paste from shadertoy.
and if it's for a desktop (Vive, Oculus... ), WebGL may be a limited (I wouldn't use it at least)

**Comment by coderofsalvation** [comment]
interesting. Was the basic demo tested on oculus Go already? (oculus browser supports webxr thru aframe these days).

**Comment by omgitsraven** [comment]
If you mean mine—I don't have access to a Go unfortunately! In theory it should just come down to the complexity of your shader though? (Depending on how simple it can get before it becomes too trivial to be interesting...)
